#docker file for next js node 16
FROM node:16-alpine3.11

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

# Install dependencies
RUN npm install --ignore-engines

# Bundle app source
COPY . .

# Expose port 3000
EXPOSE 3000

# Build the app
RUN npm run build

# Start the app
CMD [ "npm", "start" ]


