name: Build and Push Docker Image

on:
  push:
    branches:
      - test  # You can adjust this to match your main branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    env:
      NEXT_PUBLIC_MONGO_URI: ${{secrets.MONGO_URI}}
      NEXT_PUBLIC_BASE_URL: "http://socialdoze.in"
      NEXT_PUBLIC_ADMIN_USERNAME: "marvel"
      NEXT_PUBLIC_ADMIN_PASSWORD: "justiceleague"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          IMAGE_NAME: shivamsagar888/super-waffle:latest  # Replace with your Docker Hub repository and image name
        run: |
          docker build -t $IMAGE_NAME . -f DockerFile
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push $IMAGE_NAME
